# Create your models here.
from email.policy import default
from pyexpat import model
from ssl import Purpose
from statistics import mode
from django.db import models

class UserID(models.Model):
    "user_id: generated by GET /userID"
    user_id = models.CharField(max_length=64)
    def __str__(self):
        return '{}'.format(self.user_id)

class Chat(models.Model):
    "user_id: 64-length string generated by /GET userID"
    user_id = models.CharField(max_length=64)
    "chat_type: question | answer | parts"
    chat_type = models.CharField(max_length=10, auto_created=True, default="question")
    "content"
    content = models.TextField()
    "parameters"
    parameters = models.JSONField(default=dict)
    created_at = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return '{},{},{},{}'.format(self.user_id, self.chat_type, self.content, self.created_at)



class PCSpecInfo(models.Model):
    "user_id: 64-length string generated by /GET userID, primary key"
    user_id = models.CharField(max_length=64)
    "bucket_low"
    bucket_min = models.IntegerField()
    "bucket_high: "
    bucket_max = models.IntegerField()
    "purpose: set of Strings including some of the purposes: 'Gaming', 'VideoProcessing', 'Office'"


class PCParts(models.Model):
    "chat_id: foriegn key, Chat.chat_id"
    chat_id = models.ForeignKey("Chat", related_name="parts", on_delete=models.CASCADE, db_column="chat_id")
    "part_type: cpu | gpu | mainboard | ram | powersupply | disk | case"
    part_type = models.CharField(max_length=64)
    "part_name"
    part_name = models.CharField(max_length=64)
    "price"
    price = models.IntegerField()
    "shop_link"
    shop_link = models.URLField()
    "thumbnail"
    thumbnail = models.URLField()
