# Generated by Django 4.0.3 on 2022-04-13 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chat_userid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='userID',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='userid',
            old_name='userID',
            new_name='user_id',
        ),
        migrations.AlterField(
            model_name='chat',
            name='chat_type',
            field=models.CharField(auto_created=True, default='question', max_length=10),
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
